---
- name: Playbook Name
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Import Variables file
      include_vars: vars/bastion_setup

    - name: Task 2
      include_vars: vars/output_ids
      
    - name: Create a new EC2 key pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
      register: bastion_key
      
    - name: Save the private key to a file
      copy:
        content: "{{ bastion_key.key.private_key }}"
        dest: "./{{key_name}}"
        mode: '0600'

    - name: Create a new security group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{myip}}"
        tags:
          Name: BastionSG
          project: vprofile
      register: bastionSG

    - name: Launch Bastion EC2 instance
      amazon.aws.ec2_instance:
        name: Bastion_Server
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        vpc_subnet_id: "{{ public_subnet_1_id }}"
        group: "{{ bastionSG.group_id }}"
        wait: yes
        exact_count: 1
        tags:
          Name: Bastion_Server
          project: vprofile
      register: ec2_instance
      