---
- name: Create a VPC on AWS
  hosts: localhost
  gather_facts: False
  tasks:

    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{ state }}"
        tags: {"project": "vprofile"}
      register: vpc
    
    - name: Create a public subnet in zone-1a
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ pubSub1Cidr }}"
        region: "{{ region }}"
        state: present
        map_public: true
        az: "{{ az_1 }}"
        tags:
          {
          Name: vprofile-pub-sub-1,
          project: vprofile
          }
      register: public_subnet_1

    - name: Create a private subnet in zone-1a
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ priSub1Cidr }}"
        region: "{{ region }}"
        state: present
        map_public: false
        az: "{{ az_1 }}"
        tags:
          {
          Name: vprofile-priv-sub-1,
          project: vprofile
          }
      register: private_subnet_1

    - name: Create a public subnet in zone-1b
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ pubSub2Cidr }}"
        region: "{{ region }}"
        state: present
        map_public: true
        az: "{{ az_2 }}"
        tags:
          {
          Name: vprofile-pub-sub-2,
          project: vprofile
          }
      register: public_subnet_2

    - name: Create a private subnet in zone-1b
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ priSub2Cidr }}"
        region: "{{ region }}"
        state: present
        map_public: false
        az: "{{ az_2 }}"
        tags:
          {
          Name: vprofile-priv-sub-2,
          project: vprofile
          }
      register: private_subnet_2

    - name: Create a public subnet in zone-1c
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ pubSub3Cidr }}"
        region: "{{ region }}"
        state: present
        map_public: true
        az: "{{ az_3 }}"
        tags:
          {
          Name: vprofile-pub-sub-3,
          project: vprofile
          }
      register: public_subnet_3

    - name: Create a private subnet in zone-1c
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ priSub3Cidr }}"
        region: "{{ region }}"
        state: present
        map_public: false
        az: "{{ az_3 }}"
        tags:
          {
          Name: vprofile-pri-sub-3,
          project: vprofile
          }
      register: private_subnet_3

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: vprofile-IGW
          project: vprofile
      register: igw

    - name: Set up public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: vprofile-RT
          project: vprofile
        subnets:
          - "{{ public_subnet_1.subnet.id }}"
          - "{{ public_subnet_2.subnet.id }}"
          - "{{ public_subnet_3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
          - dest: ::/0
            gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table

    - name: Create new nat gateway
      amazon.aws.ec2_vpc_nat_gateway:
        state: present
        subnet_id: "{{ public_subnet_2.subnet.id }}"
        wait: true
        region: "{{ region }}"
        if_exist_do_not_create: true
        tags:
          Name: vprofile-NAT-GW
          project: vprofile
      register: new_nat_gateway

    - name: Set up private route table for NAT Gateway
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: vprofile-Nat-GW
          project: vprofile
        subnets:
          - "{{ private_subnet_1.subnet.id }}"
          - "{{ private_subnet_2.subnet.id }}"
          - "{{ private_subnet_3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ new_nat_gateway.nat_gateway_id }}"
      register: private_route_table